# Generated by Django 5.1.6 on 2025-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.CharField(default='xyz', max_length=200),
        ),
    ]
