# Generated by Django 5.1.6 on 2025-02-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0005_alter_challenge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
